apiVersion: v1
kind: Namespace
metadata:
  name:  app-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-ns
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: thedevelopcat/todolist:latest
        env:
        - name: SQL_CONNECTIONSTRING
          value: "Server=sql-service.sql-ns.svc.cluster.local,1433;Database=Master;User Id=sa;Password=My_Super_Password123"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sql-svc
  namespace: app-ns
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 80
