apiVersion: v1
kind: Namespace
metadata:
  name:  app-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-ns
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: thedevelopcat/todolist:latest
        env:
        - name: SQL_CONNECTIONSTRING
          value: "Server=sql-service.sql-ns.svc.cluster.local,1433;Database=Master;User Id=sa;Password=My_Super_Password123"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: app-ns
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
